// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laennawtvovlbtkykdoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZW5uYXd0dm92bGJ0a3lrZG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTk3MjEsImV4cCI6MjA3MjczNTcyMX0.ixgrpRZqoVDm-cS51a3aSYwgZcO3F-244F7SPNDQqMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});